ROOT_PATH=.

WS_DIR=${ROOT_PATH}
WS_NAME=RevSDK
WS_PATH=${WS_DIR}/${WS_NAME}.xcworkspace
WS_SCHEME=RevSDK

BUILD_TARGET=RevSDK
BUILD_CONFIG=Release
BUILD_EXPORT_DIR=${ROOT_PATH}/export/sdk
BUILD_DIR=${BUILD_EXPORT_DIR}/build
BUILD_OBJROOT=${BUILD_DIR}/Intermediates
BUILD_ROOT=${BUILD_DIR}
BUILD_SYMROOT=${BUILD_DIR}
BUILD_ACTION=build

SDK_IPHONEOS=iphoneos
SDK_SIMULATOR=iphonesimulator
SDK_UNIVERSAL=universal

IPHONEOS_BUILD_DIR=${BUILD_DIR}/${BUILD_CONFIG}-${SDK_IPHONEOS}
SIMULATOR_BUILD_DIR=${BUILD_DIR}/${BUILD_CONFIG}-${SDK_SIMULATOR}
UNIVERSAL_BUILD_DIR=${BUILD_DIR}/${BUILD_CONFIG}-${SDK_UNIVERSAL}

rm -rf "${BUILD_EXPORT_DIR}"
mkdir -p "${BUILD_EXPORT_DIR}"
mkdir -p "${BUILD_DIR}"

xcodebuild -workspace "${WS_PATH}" -scheme "${WS_SCHEME}" -configuration "${BUILD_CONFIG}" -sdk ${SDK_IPHONEOS} BUILD_DIR="${BUILD_DIR}" OBJROOT="${BUILD_OBJROOT}" BUILD_ROOT="${BUILD_ROOT}" CONFIGURATION_BUILD_DIR="${IPHONEOS_BUILD_DIR}" SYMROOT="${BUILD_SYMROOT}" ARCHS='arm64 armv7 armv7s' VALID_ARCHS='arm64 armv7 armv7s' ${BUILD_ACTION}

xcodebuild -workspace "${WS_PATH}" -scheme "${WS_SCHEME}" -configuration "${BUILD_CONFIG}" -sdk ${SDK_SIMULATOR} BUILD_DIR="${BUILD_DIR}" OBJROOT="${BUILD_OBJROOT}" BUILD_ROOT="${BUILD_BUILD_ROOT}" CONFIGURATION_BUILD_DIR="${SIMULATOR_BUILD_DIR}" SYMROOT="${BUILD_SYMROOT}" ARCHS='x86_64 i386' VALID_ARCHS='x86_64 i386' ${BUILD_ACTION}

mkdir -p "${UNIVERSAL_BUILD_DIR}"

cp -R "${SIMULATOR_BUILD_DIR}/${WS_SCHEME}.framework" "${UNIVERSAL_BUILD_DIR}/${WS_SCHEME}.framework"

lipo -create "${IPHONEOS_BUILD_DIR}/${WS_SCHEME}.framework/${WS_SCHEME}" "${SIMULATOR_BUILD_DIR}/${WS_SCHEME}.framework/${WS_SCHEME}" -output "${UNIVERSAL_BUILD_DIR}/${WS_SCHEME}.framework/${WS_SCHEME}"

cp -R "${UNIVERSAL_BUILD_DIR}/${WS_SCHEME}.framework" "${BUILD_EXPORT_DIR}/${WS_SCHEME}.framework"