PROJ_DIR=.
PROJ_PATH=${PROJ_DIR}/RevSDK.xcodeproj
PROJ_TARGET=RevSDK
PROJ_NAME=RevSDK
PROJ_CONFIG=Release
PROJ_EXPORT_DIR=${PROJ_DIR}/export
PROJ_BUILD_DIR=${PROJ_EXPORT_DIR}/build
PROJ_OBJROOT=${PROJ_BUILD_DIR}/Intermediates
PROJ_BUILD_ROOT=${PROJ_BUILD_DIR}
PROJ_SYMROOT=${PROJ_BUILD_DIR}
PROJ_ACTION=build

SDK_IPHONEOS=iphoneos
SDK_SIMULATOR=iphonesimulator
SDK_UNIVERSAL=universal

IPHONEOS_BUILD_DIR=${PROJ_BUILD_DIR}/${PROJ_CONFIG}-${SDK_IPHONEOS}
SIMULATOR_BUILD_DIR=${PROJ_BUILD_DIR}/${PROJ_CONFIG}-${SDK_SIMULATOR}
UNIVERSAL_BUILD_DIR=${PROJ_BUILD_DIR}/${PROJ_CONFIG}-${SDK_UNIVERSAL}

rm -rf "${PROJ_EXPORT_DIR}"

mkdir -p "${PROJ_EXPORT_DIR}"
mkdir -p "${PROJ_BUILD_DIR}"

xcodebuild -project "${PROJ_PATH}" -target "${PROJ_TARGET}" -configuration "${PROJ_CONFIG}" -sdk ${SDK_IPHONEOS} BUILD_DIR="${PROJ_BUILD_DIR}" OBJROOT="${PROJ_OBJROOT}" BUILD_ROOT="${PROJ_BUILD_ROOT}" CONFIGURATION_BUILD_DIR="${IPHONEOS_BUILD_DIR}" SYMROOT="${PROJ_SYMROOT}" ARCHS='arm64 armv7 armv7s' VALID_ARCHS='arm64 armv7 armv7s' ${PROJ_ACTION}

xcodebuild -project "${PROJ_PATH}" -target "${PROJ_TARGET}" -configuration "${PROJ_CONFIG}" -sdk ${SDK_SIMULATOR} BUILD_DIR="${PROJ_BUILD_DIR}" OBJROOT="${PROJ_OBJROOT}" BUILD_ROOT="${PROJ_BUILD_ROOT}" CONFIGURATION_BUILD_DIR="${SIMULATOR_BUILD_DIR}" SYMROOT="${PROJ_SYMROOT}" ARCHS='x86_64 i386' VALID_ARCHS='x86_64 i386' ${PROJ_ACTION}

mkdir -p "${UNIVERSAL_BUILD_DIR}"

BUILD_IPHONEOS=${PROJ_NAME}-${SDK_IPHONEOS}
BUILD_SIMULATOR=${PROJ_NAME}-${SDK_SIMULATOR}
BUILD_UNIVERSAL=${PROJ_NAME}-${SDK_UNIVERSAL}

cp -R "${SIMULATOR_BUILD_DIR}/${PROJ_NAME}.framework" "${UNIVERSAL_BUILD_DIR}/${PROJ_NAME}.framework"

lipo -create "${IPHONEOS_BUILD_DIR}/${PROJ_NAME}.framework/${PROJ_NAME}" "${SIMULATOR_BUILD_DIR}/${PROJ_NAME}.framework/${PROJ_NAME}" -output "${UNIVERSAL_BUILD_DIR}/${PROJ_NAME}.framework/${PROJ_NAME}"

cp -R "${UNIVERSAL_BUILD_DIR}/${PROJ_NAME}.framework" "${PROJ_EXPORT_DIR}/${PROJ_NAME}.framework"