# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RevSDK' do

pod 'jsoncpp', '>= 0.6.beta.0'

end

target 'RevSDKTests' do

end

